# Use an Nginx image to serve the static website
FROM nginx:latest

# Remove default Nginx content and copy your static website files
COPY my-website /usr/share/nginx/html

# Expose port 80 to serve the website
EXPOSE 80
