apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-filebrowser-pvc
  labels:
    app: filebrowser
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.filebrowser.storage.accessModes | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .Values.filebrowser.storage.size | default "5Gi" | quote }}
