apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - {{ .Values.mysql.storage.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size | default "10Gi" }}
