apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "woocommerce.fullname" . }}-phpmyadmin
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "woocommerce.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "woocommerce.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image }}
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80
