apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - {{ .Values.redis.storage.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size | default "2Gi" }}
