apiVersion: v1
kind: Service
metadata:
  name: {{ include "woocommerce.fullname" . }}
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 # Ensure targetPort matches the internal port of the container
      nodePort: 30007
      protocol: TCP
      name: http
  selector:
    {{- include "woocommerce.selectorLabels" . | nindent 4 }}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "woocommerce.fullname" . }}-filebrowser
#   labels:
#     {{- include "woocommerce.labels" . | nindent 4 }}
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80 # Ensure targetPort matches FileBrowser's internal port
#       nodePort: 30009
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "woocommerce.selectorLabels" . | nindent 4 }}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "woocommerce.fullname" . }}-phpmyadmin
#   labels:
#     {{- include "woocommerce.labels" . | nindent 4 }}
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80 # Ensure targetPort matches phpMyAdmin's internal port
#       nodePort: 30008
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "woocommerce.selectorLabels" . | nindent 4 }}
