apiVersion: apps/v1
kind: Deployment
metadata:
  name: woocommerce
spec:
  replicas: {{ .Values.woocommerce.replicas }}
  selector:
    matchLabels:
      app: woocommerce
  template:
    metadata:
      labels:
        app: woocommerce
    spec:
      containers:
      - name: woocommerce
        image: {{ .Values.woocommerce.image }}
        ports:
        - containerPort: {{ .Values.woocommerce.service.port }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        {{- range $key, $value := .Values.woocommerce.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - name: shared-data
          mountPath: /var/www/html # WooCommerce directory
      volumes:
      - name: shared-data
        emptyDir: {}
