apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: phpmyadmin
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: wordpress-mysql  # This should match the name of your MySQL service
        - name: PMA_USER
          value: wordpress        # This should match the MySQL user
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password       # This should match the password key in your secret