global: 
  scrape_interval: 1m

scrape_configs: 
  - job_name: "prometheus" 
    scrape_interval: 1m 
    static_configs: 
    - targets: ["192.168.43.200:9091"]

  - job_name: "node" 
    static_configs: 
    - targets: ["192.168.43.200:9100"]

  - job_name: "cadvisor" 
    scrape_interval: 5s 
    static_configs: 
    - targets: ["192.168.43.200:8081"]  

  - job_name: "alertmanager"
    static_configs:
    - targets: ["192.168.43.200:9093"]

#  - job_name: "kind-k8s-devsecops"
#    static_configs:
#    - targets: ["0.0.0.0:39995"]
