version: '3.8'

services:
  wordpress1:
    build:
      context: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - wordpress1_data:/var/www/html
    ports:
      - 8683:80
    networks:
      - wordpress_network1
    depends_on:
      - php-fpm

  wordpress2:
    build:
      context: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - wordpress2_data:/var/www/html
    ports:
      - 8684:80
    networks:
      - wordpress_network1
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network1

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8680:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - wordpress1
      - wordpress2
      - php-fpm
    networks:
      - wordpress_network1

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network1

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6679:6379"
    networks:
      - wordpress_network1

volumes:
  wordpress1_data:
  wordpress2_data:
  db_data:
  wordpress_data:

networks:
  wordpress_network1:
    driver: bridge
