version: '3.8'

services:
  # WordPress Instance 1
  wordpress1:
    build:
      context: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
      VIRTUAL_HOST: woocommerce.local
      LETSENCRYPT_HOST: woocommerce.local
      LETSENCRYPT_EMAIL: your-email@example.com
    volumes:
      - wordpress1_data:/var/www/html
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # WordPress Instance 2
  wordpress2:
    build:
      context: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
      VIRTUAL_HOST: woocommerce.local
      LETSENCRYPT_HOST: woocommerce.local
      LETSENCRYPT_EMAIL: your-email@example.com
    volumes:
      - wordpress2_data:/var/www/html
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # MySQL Database
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8681:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

  # Redis for caching
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6679:6379"

    # NGINX Proxy for Load Balancing and SSL
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "8680:80"
      - "8643:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx-proxy:/etc/nginx/conf.d:ro   # Mount custom NGINX configuration
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html


  # Let's Encrypt Companion for SSL Certificates
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html

volumes:
  wordpress1_data:
    driver: local
  wordpress2_data:
    driver: local
  db_data:
    driver: local
  proxy-certs:
    driver: local
  proxy-vhost:
    driver: local
  proxy-html:
    driver: local
