apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-filebrowser
  labels:
    app: filebrowser
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.filebrowser.service.type | default "ClusterIP" }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: filebrowser
    app.kubernetes.io/instance: {{ .Release.Name }}
