apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image }}
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ .Values.mysql.auth.database | default "mysql" }}
            - name: PMA_PORT
              value: "3306"
