apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: {{ .Values.phpmyadmin.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: phpmyadmin
