apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-woocommerce
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: woocommerce
spec:
  accessModes:
    - {{ .Values.woocommerce.storage.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.woocommerce.storage.size | default "5Gi" }}
  storageClassName: {{ .Values.woocommerce.storage.storageClass | default "standard" }}
