version: '3.8'

services:
  # WooCommerce application (PHP + Apache)
  woocommerce:
    build:
      context: .
    container_name: woocommerce
    depends_on:
      - db
    networks:
      - woocommerce-network
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: woocommerce
      WORDPRESS_DB_USER: woocommerce
      WORDPRESS_DB_PASSWORD: woocommerce
    deploy:
      replicas: 3  # Scale to 3 WooCommerce containers
      restart_policy:
        condition: on-failure

  # MySQL Database for WooCommerce
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: woocommerce
      MYSQL_USER: woocommerce
      MYSQL_PASSWORD: woocommerce
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - woocommerce-network

  # PhpMyAdmin for managing the database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: woocommerce
      PMA_PASSWORD: woocommerce
    ports:
      - "8686:80"
    depends_on:
      - db
    networks:
      - woocommerce-network

  # Load Balancer (Nginx as an example)
  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "8687:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - woocommerce
    networks:
      - woocommerce-network

networks:
  woocommerce-network:
    driver: bridge

volumes:
  mysql-data:
