route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'jahidak47@gmail.com'
        auth_password: "1921125655"
        from: 'jahidak47@gmail.com'
        to: 'mdjahidhasan919@gmail.com'
