apiVersion: apps/v1
kind: Deployment
metadata:
  name: woocommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: woocommerce
  template:
    metadata:
      labels:
        app: woocommerce
    spec:
      containers:
      - name: woocommerce
        image: hmjahid/custom-woocommerce:latest
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_NAME
            value: woocommerce_db
          - name: WORDPRESS_DB_USER
            value: woocommerce_user
          - name: WORDPRESS_DB_PASSWORD
            value: dbpassword
          - name: WORDPRESS_REDIS_HOST
            value: redis
        ports:
          - containerPort: 80
        volumeMounts:
          - name: shared-woocommerce-files
            mountPath: /var/www/html/wp-content/uploads
      volumes:
        - name: shared-woocommerce-files
          emptyDir: {}
